version: '3'

services:
  subscriber-service:
    image: koa-ts-docker-subscriber
    build: './subscriber'
    depends_on:
      - rabbitmq-server
    # Override the Dockerfile CMD so that we automatically refresh code in bound volumes
    command: pm2-runtime start ecosystem.config.js
    restart: always
    # Bind our dev folder to a mount point on the container. Locally updated files (e.g. new TS
    # transpiled files) will appear in the container and be picked up by PM2 (could also use nodemon)
    volumes:
      - ./subscriber:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000

  publisher-service:
    image: koa-ts-docker-publisher
    build: './publisher'
    depends_on:
      - rabbitmq-server
    command: pm2-runtime start ecosystem.config.js
    restart: always
    volumes:
      - ./publisher:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 3001
    ports:
      - 3001:3001

  rabbitmq-server:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
