version: '3'

services:

# Python PDF processing service (AMQP subscriber and node-amqp-publisher using Pika)
  pdf-processing-service:
    image: pdf-processing-service-image
    build: './pdf-processing-service'
    depends_on:
      - rabbitmq-server
    restart: always
    environment:
      PORT: 3002
      PYTHONUNBUFFERED: 0
    ports:
      - 3002:3002


# Node/Nestjs PDF upload and AMQP publisher service
  pdf-upload-service:
    image: upload-service-image
    build: './upload-service'
    depends_on:
      - rabbitmq-server
    restart: always
    volumes:
      - ./upload-service:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 3001
    ports:
      - 3001:3001


# THIS WON'T WORK unless the pdf-processing-service is publicly accessible
  ui-service:
    image: ui-service-image
    build: './ui-service'
    depends_on:
      - rabbitmq-server
    restart: always
#    volumes:
#      - ./ui-service/dist:/usr/share/nginx/html
    environment:
      PORT: 80
      # This will be the public address of the upload service in a production environment
      UPLOAD_HOST: "http://localhost:3001/upload"
    ports:
      - 80:80


  rabbitmq-server:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
