version: '2.1'

services:
  koa-ts-docker-subscriber-service:
    build: .
    # Override the Dockerfile CMD so that we automatically refresh code in bound volumes
    command: pm2-runtime start ecosystem.config.js
    restart: always
    # Bind our dev folder to a mount point on the container. Locally updated files (e.g. new TS 
    # transpiled files) will appear in the container and be picked up by PM2 (could also use nodemon)
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 3001
    ports:
      - 3001:3001
